server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://juanpabloalvis@bitbucket.org/juanpabloalvis/configurations.git
          default-label: master
          clone-on-start: true
