server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://juanpabloalvis@bitbucket.org/juanpabloalvis/configurations.git
          clone-on-start: true
#          refresh-rate: 600
#          delete-untracked-branches: true
          default-label: master
